name: dncloud-#HOSTNAME

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.modules:
- module: docker
  metricsets:
    - cpu
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 1m
  enabled: true

  # If set to true, replace dots in labels with `_`.
  labels.dedot: false

  # If set to true, collects metrics per core.
  cpu.cores: true

processors:
- add_host_metadata:
    netinfo.enabled: false
    cache.ttl: 5m
    geo:
      name: #HOST_FULL_NAME
      country_name: #COUNTRY_NAME
      region_name: #REGION_NAME
      city_name: #CITY_NAME

- drop_fields:
    fields: ["host.os"]

output.logstash:
  hosts: ["logstash:5044"]

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
  hosts: ['https://es-cn-v6417hyip000nj8i6.public.elasticsearch.aliyuncs.com:9200']
  username: monitoring
  password: 3tOjRV%^Tu^6

