name: dncloud-#HOSTNAME

nvidiagpubeat:
  # Defines how often an event is sent to the output
  period: 1s
  query: "utilization.gpu,utilization.memory,memory.total,memory.free,memory.used,temperature.gpu,pstate"
  env: "production"
  # env can be test or production. test is for test purposes to evaluate funcationality of this beat. Switch to production
  # when you want to run this beat on a Nvidia GPU machine with SMI driver installed.

processors:
- add_host_metadata:
    netinfo.enabled: false
    cache.ttl: 5m
    geo:
      name: #HOST_FULL_NAME
      country_name: #COUNTRY_NAME
      region_name: #REGION_NAME
      city_name: #CITY_NAME

- drop_fields:
    fields: ["host.os"]

output.logstash:
  hosts: ["logstash:5044"]
