version: '3.5'
services:
  nginx:
    container_name: 'nginx'
    image: nginx:1.17.0-alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - static-files:/usr/share/nginx/html/ayes
      - /home/dntech/conf/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      standalone:
        aliases:
          - dncloud-#HOSTNAME.nginx

  ayes-fe:
    container_name: 'ayes-fe'
    image: registry.cn-shenzhen.aliyuncs.com/dntech/ayes-fe:latest
    restart: unless-stopped
    tty: true
    environment:
      - ENVIRONMENT=hospital
      - API_PROTOCOL=http
      - API_HOST=#HOST_IP_ADDRESS
      - API_SUFFIX=api
    volumes:
      - static-files:/usr/share/nginx/html
    networks:
      - standalone

  ayes-be:
    container_name: 'ayes-be'
    image: registry.cn-shenzhen.aliyuncs.com/dntech/ayes-be:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ayes-original:/var/dntech/ayes/original
      - ayes-download:/var/dntech/ayes/download
      - ayes-instance:/var/dntech/ayes/instance
      - ayes-share-celery:/var/dntech/ayes/share_detection
      - /mnt/Storage:/var/dntech/ayes/Storage
      - /home/dntech/conf/ayes-server.yml:/var/dntech/ayes/conf/system_linux.yml
      - /home/dntech/conf/ayes-dicom.yml:/var/dntech/ayes/conf/dcmtool.yml
      - /tmp/dntech/jobrun:/var/dntech/ayes/jobrun
      - /var/log/ayes:/var/dntech/ayes/log
      - /home/dntech/conf/ayes-celeryconfig.yml:/var/dntech/ayes/conf/celery_config.yml
    networks:
      standalone:
        aliases:
          - dncloud-#HOSTNAME.ayes-be
    depends_on:
      - mongo
      - minio
    command: /opt/dntech/ayes/scripts/start-ayes.sh passive
    ports:
      - 6060:6060
      - 6070:6070
      - 6078:6078
      - 6090:6090
  ayes-detection:
    container_name: 'ayes-detection'
    image: registry.cn-shenzhen.aliyuncs.com/dntech/ayes-ai:develop
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ayes-instance:/var/dntech/ayes/instance
      - ayes-share-celery:/var/dntech/ayes/share_detection
      - /home/dntech/conf/ayes-celeryconfig.yml:/var/dntech/ayes/conf/celery_config.yml
    networks:
      - standalone
    command: /dianneiAI/task.sh detection
    tty: true
  ayes-followup:
    container_name: 'ayes-followup'
    image: registry.cn-shenzhen.aliyuncs.com/dntech/ayes-ai:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ayes-instance:/var/dntech/ayes/instance
      - ayes-share-celery:/var/dntech/ayes/share_detection
      - /home/dntech/conf/ayes-celeryconfig.yml:/var/dntech/ayes/conf/celery_config.yml
    networks:
      - standalone
    command: /dianneiAI/task.sh followup 
    tty: true
  mongo:
    container_name: 'mongo'
    image: mongo:4.1.13-bionic
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongostorage
    volumes:
      - mongo-config:/data/configdb
      - mongo-storage:/data/db
    networks:
      standalone:
        aliases:
          - dncloud-#HOSTNAME.mongo
    ports:
      - 27017:27017

  mongo-express:
    container_name: 'mongo-express'
    image: mongo-express:0.49.0
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai  
      - ME_CONFIG_SITE_BASEURL=/mongo/
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongostorage
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongoexpress
    networks:
      - standalone
    depends_on:
      - mongo

  minio:
    container_name: 'minio'
    image: minio/minio:RELEASE.2019-06-19T18-24-42Z
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniostorage
    volumes:
      - minio-storage:/data
    networks:
      standalone:
        aliases:
          - dncloud-#HOSTNAME.minio
    ports:
      - 9000:9000
    command: server /data
  rabbitmq:
    container_name: 'rabbitmq'
    hostname: 'dntech-rabbitmq'
    image: rabbitmq:3.7-management-alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=alice
      - RABBITMQ_DEFAULT_PASS=wonderland
    volumes:
      - rabbitmq-storage:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      standalone:
        aliases:
          - dncloud-#HOSTNAME.rabbitmq

volumes:
  static-files:
    name: static-files
  ayes-instance:
    name: ayes-instance
  ayes-share-celery:
    name: ayes-share-celery
  ayes-original:
    name: ayes-original
  ayes-download:
    name: ayes-download
  mongo-config:
    name: mongo-config
  mongo-storage:
    name: mongo-storage
  minio-storage:
    name: minio-storage
  rabbitmq-storage:
    name: rabbitmq-storage

networks:
  standalone:
    name: standalone

